- id: mix-format
  name: mix format
  description: Formats Elixir files with mix format.
  language: system
  entry: mix format
  files: \.exs?$

- id: mix-test
  name: mix test
  description: Runs Elixir tests with mix test.
  language: system
  entry: mix test
  files: \.ex$

- id: mix-credo
  name: mix credo
  description: Runs credo static analysis with mix credo.
  language: system
  entry: mix credo
  files: \.ex$

- id: mix-dialyxir
  name: mix dialyxir
  description: Runs the dialyxir static analysis tool. Use with caution as can be slow.
  language: system
  entry: mix dialyxir
  files: \.ex$

- id: mix-escript-build
  name: mix escript.build
  description: Build escript when script or module source changes.
  language: system
  entry: mix escript.build
  files: \.exs?$

- id: mix-sobelow
  name: mix sobelow
  description: Runs Sobelow security scanner.
  language: system
  entry: mix sobelow
  files: \.exs?$
